from datetime import datetime
from sqlalchemy.orm import Session
from database import AlertDB
from models import AlertCreate


def build_alert_payload(analysis: dict) -> dict:
    return {
        "channel_name": analysis.get("channel", "Unknown channel"),
        "threat_level": analysis.get("threat_level", "UNKNOWN"),
        "confidence": float(analysis.get("confidence", 0)),
        "risk_score": float(analysis.get("risk_score", 0)),
        "content_type": analysis.get("content_type", "Unknown"),
        "reasoning": analysis.get("reasoning", "Analysis generated by DRISHTI."),
        "recommended_action": analysis.get("recommended_action", "Human verification required."),
        "cluster_score": float(analysis.get("cluster_score", 0)),
        "propagation_score": float(analysis.get("propagation_score", 0))
    }


def save_alert(db: Session, payload: dict) -> AlertDB:
    alert = AlertDB(
        timestamp=datetime.utcnow(),
        channel_name=payload["channel_name"],
        threat_level=payload["threat_level"],
        confidence=payload["confidence"],
        risk_score=payload["risk_score"],
        content_type=payload["content_type"],
        reasoning=payload["reasoning"],
        recommended_action=payload["recommended_action"],
        cluster_score=payload["cluster_score"],
        propagation_score=payload["propagation_score"],
        status="NEW"
    )
    db.add(alert)
    db.commit()
    db.refresh(alert)
    return alert


def serialize_alert(alert: AlertDB) -> dict:
    return {
        "id": alert.id,
        "timestamp": alert.timestamp.isoformat(),
        "channel_name": alert.channel_name,
        "threat_level": alert.threat_level,
        "confidence": alert.confidence,
        "risk_score": alert.risk_score,
        "content_type": alert.content_type,
        "reasoning": alert.reasoning,
        "recommended_action": alert.recommended_action,
        "cluster_score": alert.cluster_score,
        "propagation_score": alert.propagation_score,
        "status": alert.status
    }
